language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker

install:
- curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
    gradle check
 - ./run 'docker build -t test . && docker run test'
 
branches:
only: master

