language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker

install:
 - docker build -t myContainer .

#script:
# - ./run 'docker build -t test . && docker run test'
script:
  - docker exec -ti myContainer "BitCountingTest.java"

branches:
only: master

